# Generated by Django 4.0.5 on 2022-06-10 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('given_name', models.CharField(max_length=20)),
                ('ID_Number', models.IntegerField(null=True)),
                ('combination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
                ('coverage', models.CharField(choices=[('0', '0'), ('25', '25'), ('75', '75'), ('100', '100')], max_length=10)),
                ('subject', models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='school_eyes.subject')),
            ],
        ),
    ]
