# Generated by Django 4.0.5 on 2022-06-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User',
        ),
    ]
