# Generated by Django 4.0.5 on 2022-06-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0007_rename_user_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
