# Generated by Django 4.0.5 on 2022-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0008_rename_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.TextField(default='25'),
        ),
    ]
